package com.android.mr.githubexplorer.ui.search

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.android.mr.githubexplorer.graphql.SearchUserQuery
import com.android.mr.githubexplorer.network.apolloClient
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch


/**
 * Represents the state of the search screen.
 *
 * SearchUserQuery(login = login) — that Kotlin class was auto-generated by Apollo from
 * SearchUser.graphql file. The parameter name login maps directly to the $login variable declared
 * in the .graphql file. If you rename the variable in the file and rebuild,
 * this call site becomes a compile error.
 */
sealed interface SearchUiState {
    data object Idle: SearchUiState
    data object Loading: SearchUiState
    data class Success(val user: SearchUserQuery.User): SearchUiState
    data class Error(val message: String): SearchUiState
}

class SearchViewModel : ViewModel() {

    private var _uiState = MutableStateFlow<SearchUiState>(SearchUiState.Idle)
    val uiState: StateFlow<SearchUiState> = _uiState.asStateFlow()

    fun search(login: String) {
        viewModelScope.launch {
            _uiState.value = SearchUiState.Loading

            // Execute GraphQL query — Apollo generates SearchUserQuery from SearchUser.graphql
            val response = apolloClient
                .query(SearchUserQuery(login))
                .execute()

            val user = response.data?.user
            _uiState.value = when {
                response.hasErrors() -> SearchUiState.Error(
                    response.errors?.firstOrNull()?.message ?: "GraphQL Error")
                user == null -> SearchUiState.Error("User \"$login\" not found")
                else -> SearchUiState.Success(user)
            }
        }
    }
}